Repository enthought/comtypes, pull requests merged in 2023-01, with the labels that each got.

#440 add tests for `client.dynamic`
  comtypes/test/test_client_dynamic.py
Labels: drop_py2

#442 fix `client.dynamic._Dispatch.QueryInterface`
  comtypes/client/dynamic.py
Labels: drop_py2

#444 add type annotations to `client.dynamic` other than `Dispatch` function
  comtypes/client/dynamic.py
Labels: drop_py2

#448 fix importing `typing` under `if TYPE_CHECKING:`
  comtypes/__init__.py
  comtypes/_memberspec.py
  comtypes/automation.py
  comtypes/client/__init__.py
  comtypes/client/_generate.py
  comtypes/tools/codegenerator.py
  comtypes/tools/tlbparser.py
  comtypes/tools/typedesc.py
  comtypes/tools/typedesc_base.py
  comtypes/typeinfo.py
Labels: drop_py2

#451 fix `IPersist.GetClassID` to `TYPE_CHECKING` only method from `Callable` annotation
  comtypes/__init__.py
Labels: drop_py2

#452 remove `unittest.skip` marks from `test_client.Test_CreateObject`
  comtypes/test/test_client.py
Labels: drop_py2

#453 change type hints in `comtypes/__init__.py` for each function that needs `@overload` to inline annotations
  comtypes/__init__.py
Labels: drop_py2

#454 change type hints from comment annotations to inline annotations in `comtypes/__init__.py`, `comtypes/automation.py` and `comtypes/typeinfo.py`
  comtypes/__init__.py
  comtypes/automation.py
  comtypes/typeinfo.py
Labels: drop_py2

#455 change type hints from comment annotations to inline annotations in `_memberspec`
  comtypes/_memberspec.py
Labels: drop_py2

#456 change type hints from comment annotations to inline annotations in `comtypes/client/...`
  comtypes/client/__init__.py
  comtypes/client/_generate.py
Labels: drop_py2

#457 Update `codegenerator` type annotations
  comtypes/tools/codegenerator.py
Labels: drop_py2

#459 Update `tlbparser` type annotations
  comtypes/tools/tlbparser.py
Labels: drop_py2

#461 Update type annotations in `typedesc` and `typedesc_base`
  comtypes/tools/typedesc.py
  comtypes/tools/typedesc_base.py
Labels: drop_py2

#462 fix `test_getactiveobj` and remove raising `unittest.SkipTest`
  comtypes/test/test_getactiveobj.py
Labels: tests, drop_py2

#465 add `black` style checking to GHA settings
  .github/workflows/autofmt.yml
Labels: drop_py2

#466 modernize `test_client`
  comtypes/test/test_client.py
Labels: drop_py2

#467 fix `__next__()` in IEnum code generator
  comtypes/tools/codegenerator.py
Labels: drop_py2

#470 Correcting type hint for CreateObject
  comtypes/client/__init__.py
Labels: drop_py2

#471 Add unit test for generated IEnum (#468)
  comtypes/test/test_ienum.py
Labels: tests, drop_py2

#469 make explicit the symbols that imports from the wrapper module into the friendly module
  comtypes/client/_generate.py
  comtypes/tools/codegenerator.py
Labels: enhancement, drop_py2
