Repository enthought/comtypes, pull requests merged in 2024-12, with the labels that each got.

#674 Improve skipping `test_server`.
  comtypes/test/test_server.py
Labels: tests

#676 Split `server/w_getopt.py` (part 1 of #675).
  comtypes/server/_w_getopt.py
  comtypes/server/register.py
  comtypes/test/test_w_getopt.py
Labels: tests

#675 Split `server/w_getopt.py`.
  comtypes/server/register.py
  comtypes/server/w_getopt.py
  comtypes/test/test_w_getopt.py
Labels: tests

#678 Fix broken unregistration of 64bit type libraries (second attempt)
  comtypes/typeinfo.py
Labels: enhancement, 64-bit

#679 Improve static typing for `test_excel`.
  comtypes/test/test_excel.py
Labels: tests, typing

#680 Revive `test_comserver`.
  comtypes/test/test_comserver.py
Labels: tests

#681 Remove `SixDocChecker` from `test_showevents`.
  comtypes/test/test_showevents.py
Labels: tests

#682 Set `verbose=False` into `doctest.testmod` to suppress the output.
  comtypes/test/test_comserver.py
Labels: tests

#683 Revive `test_dispinterface`.
  comtypes/test/test_dispinterface.py
Labels: tests

#685 Separate the parts of `test_safearray` that depend on `pythoncom` into a different module (part 1 of #684).
  comtypes/test/test_safearray_.py
  comtypes/test/test_safearray_pywin32.py
Labels: tests

#684 Separate the parts of `test_safearray` that depend on `pythoncom` into a different module.
  comtypes/test/test_safearray.py
  comtypes/test/test_safearray_pywin32.py
Labels: tests

#686 Remove `is_resource_enabled` and `requires` from tests.
  comtypes/test/test_BSTR.py
  comtypes/test/test_comserver.py
  comtypes/test/test_createwrappers.py
  comtypes/test/test_ie.py
  comtypes/test/test_outparam.py
  comtypes/test/test_win32com_interop.py
  comtypes/test/test_wmi.py
Labels: tests

#687 Add `LP_SAFEARRAY.from_param` to `hints.pyi`.
  comtypes/hints.pyi
Labels: typing

#689 Add `pip install pywin32` to CI pipelines.
  .github/workflows/autotest.yml
Labels: tests

#690 `test_win32com_interop` does not depend on IE no more.
  comtypes/test/test_win32com_interop.py
Labels: tests

#691 Move tests and fixtures from `test_safearray_pywin32` to `test_win32com_interop`.
  comtypes/test/test_safearray_pywin32.py
  comtypes/test/test_win32com_interop.py
Labels: tests

#693 Add `IMPORT_PYWIN32_FAILED` flags to `test_dispinterface` and `test_comserver`.
  comtypes/test/test_comserver.py
  comtypes/test/test_dispinterface.py
Labels: tests

#695 Move some tests to `test_comserver`.
  comtypes/test/test_comserver.py
  comtypes/test/test_propputref.py
  comtypes/test/test_safearray.py
  comtypes/test/test_variant.py
Labels: tests

#697 Separate the `Registrar._registry_entries` method into an iterator class.
  comtypes/server/register.py
  comtypes/test/test_server_register.py
Labels: enhancement, tests, typing

#698 Add tests for `RegistryEntries`.
  comtypes/test/test_server_register.py
Labels: tests

#701 Add type annotations to `server/w_getopt.py`.
  comtypes/server/w_getopt.py
Labels: typing

#704 Add type hints to `_comobject.py` (part 2).
  comtypes/_comobject.py
  comtypes/hints.pyi
Labels: typing

#705 Add type hints to `_comobject.py` (part 3).
  comtypes/_comobject.py
Labels: typing

#706 Add type hints to `_comobject.py` (part 4).
  comtypes/_comobject.py
Labels: typing

#708 Add type hints to `server/inprocserver.py` and `server/localserver.py`.
  comtypes/server/inprocserver.py
  comtypes/server/localserver.py
Labels: typing

#710 Add `test_comobject`(part 2).
  comtypes/_comobject.py
  comtypes/test/test_comobject.py
Labels: tests, typing

#711 Add `test_comobject`(part 3).
  comtypes/_comobject.py
  comtypes/test/test_comobject.py
Labels: tests, typing

#718 Improve typing and import sources.
  comtypes/_comobject.py
  comtypes/_memberspec.py
  comtypes/_post_coinit/unknwn.py
  comtypes/_vtbl.py
  comtypes/automation.py
  comtypes/test/test_inout_args.py
Labels: typing, coding style

#719 Add RTD configuration files.
  .readthedocs.yaml
  docs/requirements.txt
Labels: shared_info

#720 Update client-side documentation.
  .github/workflows/autotest.yml
  .gitignore
  docs/requirements.txt
  docs/source/conf.py
  docs/source/index.rst
  docs/source/scriptcontrol.rst
Labels: shared_info

#721 Update server-side documentation.
  .github/workflows/autotest.yml
  docs/source/conf.py
  docs/source/index.rst
  docs/source/server.rst
Labels: shared_info

#723 Split documentation into multiple pages (part 1 of #722).
  docs/source/client.rst
  docs/source/conf.py
  docs/source/main.rst
Labels: shared_info

#724 Split documentation into multiple pages (part 2 of #722).
  docs/source/client.rst
  docs/source/main.rst
Labels: shared_info

#725 Split documentation into multiple pages (part 3 of #722).
  docs/source/conf.py
  docs/source/index.rst
  docs/source/npsupport.rst
  docs/source/threading.rst
Labels: shared_info

#726 Split documentation into multiple pages (part 4 of #722).
  docs/source/index.rst
  docs/source/npsupport.rst
  docs/source/threading.rst
Labels: shared_info

#722 Split documentation into multiple pages.
  docs/source/client.rst
  docs/source/com_interfaces.rst
  docs/source/index.rst
  docs/source/server.rst
Labels: shared_info

#727 Change readthedocs sphinx theme.
  .readthedocs.yaml
  docs/source/client.rst
  docs/source/com_interfaces.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/server.rst
Labels: shared_info

#728 Mention that it is unnecessary to `Release` created or copied objects in documentation.
  docs/source/client.rst
  docs/source/com_interfaces.rst
  docs/source/conf.py
Labels: shared_info

#729 Improve documents.
  docs/source/com_interfaces.rst
  docs/source/index.rst
  docs/source/server.rst
Labels: shared_info
