Repository enthought/comtypes, pull requests merged in 2024-01, with the labels that each got.

#502 add `Python312`s to ci pipeline
  appveyor.yml
Labels: drop_py2

#473 Fix old index bug in `call_with_inout`
  comtypes/_memberspec.py
  comtypes/test/test_imfattributes.py
  comtypes/test/test_inout_args.py
  comtypes/test/test_outparam.py
Labels: tests, drop_py2

#508 Update "Ongoing plans" in `README.md`
  README.md
Labels: shared_info
