Repository enthought/comtypes, pull requests merged in 2024-10, with the labels that each got.

#630 Use `self` instead of `klass`/`new_cls` in the `__new__` of metaclasses.
  comtypes/_meta.py
  comtypes/_post_coinit/unknwn.py
Labels: coding style

#632 Adopt `ruff` formatter and linter.
  .github/workflows/autofmt.yml
  README.md
  comtypes/_comobject.py
  comtypes/_memberspec.py
  comtypes/_npsupport.py
  comtypes/_post_coinit/__init__.py
  comtypes/_post_coinit/misc.py
  comtypes/_post_coinit/unknwn.py
  comtypes/client/__init__.py
  comtypes/client/_code_cache.py
  comtypes/git.py
  comtypes/hints.pyi
  comtypes/persist.py
  comtypes/server/__init__.py
  comtypes/server/register.py
  comtypes/shelllink.py
  comtypes/test/TestComServer.py
  comtypes/test/TestDispServer.py
  comtypes/test/test_clear_cache.py
  comtypes/test/test_dispinterface.py
  comtypes/test/test_server.py
  comtypes/test/test_urlhistory.py
  comtypes/tools/codegenerator/typeannotator.py
  comtypes/tools/typedesc.py
  comtypes/typeinfo.py
  comtypes/util.py
  pyproject.toml
Labels: coding style

#634 Add `@overload`s to `ImportedNamespaces.add`.
  comtypes/tools/codegenerator/namespaces.py
Labels: typing

#626 Prevent errors caused by defining members with the same name within an enum type.
  comtypes/tools/codegenerator/namespaces.py
Labels: bug

#641 Refactored `itf.__dict__` to `vars(itf)`
  comtypes/_post_coinit/unknwn.py
Labels: typing

#636 Modify the metaclasses to ensure compatibility with Python 3.13 and earlier versions.
  .github/workflows/autotest.yml
  comtypes/_meta.py
  comtypes/_post_coinit/unknwn.py
  comtypes/safearray.py
Labels: enhancement, tests
