Repository enthought/comtypes, pull requests merged in 2024-11, with the labels that each got.

#651 Replace `Literal` and `Protocol` with runtime-referable symbols.
  comtypes/hints.pyi
  comtypes/shelllink.py
  comtypes/tools/codegenerator/typeannotator.py
Labels: typing

#654 Refactor from `%` string formatting to f-strings in `_post_coinit.unknwn`.
  comtypes/_post_coinit/unknwn.py
Labels: coding style

#645 Remove workarounds for importing safearrays. (#640)
  comtypes/automation.py
Labels: coding style

#666 Refactor string formatting to use f-strings
  comtypes/_comobject.py
  comtypes/_memberspec.py
  comtypes/_post_coinit/_cominterface_meta_patcher.py
  comtypes/automation.py
Labels: coding style

#667 Updating by fstring
  comtypes/client/_code_cache.py
  comtypes/client/_constants.py
  comtypes/client/_events.py
  comtypes/client/_generate.py
  comtypes/client/lazybind.py
  comtypes/errorinfo.py
  comtypes/server/inprocserver.py
  comtypes/server/register.py
  comtypes/server/w_getopt.py
  comtypes/tools/codegenerator/codegenerator.py
  comtypes/tools/codegenerator/helpers.py
Labels: coding style

#670 Allow the definition of the `_midlSAFEARRAY(HRESULT)` type.
  comtypes/automation.py
  comtypes/safearray.py
  comtypes/test/test_midl_safearray_create.py
Labels: enhancement
