Repository enthought/comtypes, pull requests merged in 2024-07, with the labels that each got.

#578 Implement static import for `ISequentialStream` (#474)
  comtypes/client/_generate.py
  comtypes/stream.py
  comtypes/test/test_client.py
  comtypes/test/test_istream.py
Labels: enhancement

#580 add static typing for `_midlSAFEARRAY`
  comtypes/_safearray.py
  comtypes/automation.py
  comtypes/hints.pyi
  comtypes/safearray.py
Labels: typing

#583 Add tests and method annotations for `IRecordInfo`
  comtypes/test/test_recordinfo.py
  comtypes/typeinfo.py
Labels: tests, typing

#584 Improve static typings in `automation`
  comtypes/automation.py
Labels: typing

#585 Tidy up import part in some modules.
  comtypes/_memberspec.py
  comtypes/client/__init__.py
  comtypes/hints.pyi
  comtypes/tools/codegenerator/typeannotator.py
  comtypes/tools/typedesc_base.py
  comtypes/typeinfo.py
Labels: typing

#586 Refer to `Any` and `Tuple` from the `hints` stub instead of directly importing them in generated modules.
  comtypes/hints.pyi
  comtypes/tools/codegenerator/codegenerator.py
  comtypes/tools/codegenerator/typeannotator.py
Labels: typing

#587 Modernize `GUID.py`
  comtypes/GUID.py
  comtypes/hints.pyi
Labels: typing

#590 Improve `codegenerator.modulenamer` static typing.
  comtypes/tools/codegenerator/modulenamer.py
Labels: typing
