Repository enthought/comtypes, pull requests merged in 2024-05, with the labels that each got.

#537 Refactoring `test_findgendir`
  comtypes/test/test_findgendir.py
Labels: tests

#538 update `test_GUID`
  comtypes/test/test_GUID.py
Labels: tests

#539 Add a feature to `typeannotator` that interprets the return value
  comtypes/tools/typeannotator.py
Labels: enhancement, typing

#540 update type annotations for `_IUnknown_Base` and `IUnknown`
  comtypes/__init__.py
Labels: typing

#542 add static typing for when a `CoClass` is assigned as the return value type
  comtypes/hints.pyi
  comtypes/tools/typeannotator.py
Labels: typing

#535 Implement record pointers as method parameters of a Dispatch Interface
  .github/workflows/autotest.yml
  comtypes/automation.py
  comtypes/test/test_dispifc_records.py
  source/CppTestSrv/CFACTORY.CPP
  source/CppTestSrv/CFACTORY.H
  source/CppTestSrv/CUNKNOWN.CPP
  source/CppTestSrv/CUNKNOWN.H
  source/CppTestSrv/CoComtypesDispIfcParamTests.cpp
  source/CppTestSrv/CoComtypesDispIfcParamTests.h
  source/CppTestSrv/MAKEFILE
  source/CppTestSrv/OUTPROC.CPP
  source/CppTestSrv/REGISTRY.CPP
  source/CppTestSrv/REGISTRY.H
  source/CppTestSrv/SERVER.CPP
  source/CppTestSrv/SERVER.IDL
  source/CppTestSrv/UTIL.CPP
  source/CppTestSrv/UTIL.H
Labels: enhancement, tests
