Repository enthought/comtypes, pull requests merged in 2025-06, with the labels that each got.

#841 CI/CD Improvements for runners and the codecov badge.
  .github/workflows/autotest.yml
  README.md
Labels: tests, ci

#842 Add signed 32-bit hexadecimal converters.
  comtypes/hresult.py
  comtypes/test/test_hresult.py
Labels: enhancement

#843 Add ``Test_Stat`` to ``test_stream``.
  comtypes/test/test_stream.py
Labels: tests

#845 Add client-side `RegisterActiveObject`.
  comtypes/__init__.py
  comtypes/_post_coinit/activeobj.py
  comtypes/_post_coinit/misc.py
  comtypes/client/__init__.py
  comtypes/client/_activeobj.py
  comtypes/server/__init__.py
  comtypes/server/localserver.py
  comtypes/test/test_getactiveobj.py
Labels: enhancement

#846 Run ruff check UP004
  comtypes/_comobject.py
  comtypes/_memberspec.py
  comtypes/_post_coinit/_cominterface_meta_patcher.py
  comtypes/_vtbl.py
  comtypes/automation.py
  comtypes/client/_constants.py
  comtypes/client/_events.py
  comtypes/client/_generate.py
  comtypes/client/dynamic.py
  comtypes/client/lazybind.py
  comtypes/messageloop.py
  comtypes/patcher.py
  comtypes/safearray.py
  comtypes/server/connectionpoints.py
  comtypes/server/register.py
  comtypes/test/test_comserver.py
  comtypes/test/test_excel.py
  comtypes/test/test_server.py
  comtypes/test/test_urlhistory.py
  comtypes/test/test_word.py
  comtypes/tools/codegenerator/codegenerator.py
  comtypes/tools/codegenerator/comments.py
  comtypes/tools/codegenerator/heads.py
  comtypes/tools/codegenerator/helpers.py
  comtypes/tools/codegenerator/namespaces.py
  comtypes/tools/codegenerator/typeannotator.py
  comtypes/tools/tlbparser.py
  comtypes/tools/typedesc.py
  comtypes/tools/typedesc_base.py
Labels: coding style

#854 Skip unstable `test_eval` in INPROC server tests.
  comtypes/test/test_comserver.py
Labels: tests
