Repository enthought/comtypes, pull requests merged in 2025-01, with the labels that each got.

#730 Add `Test_Registrar_...`.
  comtypes/test/test_server_register.py
Labels: tests

#731 Small refactoring for `RegistryEntries`.
  comtypes/server/register.py
Labels: coding style

#733 Replace `GetModuleFileNameA` with `GetModuleFileNameW` to prevent a `TypeError`.
  comtypes/server/register.py
  comtypes/test/test_server_register.py
  comtypes/test/test_typeinfo.py
  comtypes/typeinfo.py
Labels: tests

#734 Improve typings in `server/register.py`.
  comtypes/server/register.py
Labels: typing

#743 Refactor `server.register`.
  comtypes/server/register.py
  comtypes/test/test_server_register.py
Labels: tests, typing, coding style

#746 Reserving blank lines in the generated modules (part 1 of #745).
  comtypes/tools/codegenerator/__init__.py
  comtypes/tools/codegenerator/comments.py
  comtypes/tools/codegenerator/generator.py
  pyproject.toml
Labels: typing, coding style

#747 Reserving blank lines in the generated modules (part 2 of #745).
  comtypes/tools/codegenerator/__init__.py
  comtypes/tools/codegenerator/codegenerator.py
  comtypes/tools/codegenerator/heads.py
  pyproject.toml
Labels: typing, coding style

#748 Reserving blank lines in the generated modules (part 3 of #745).
  comtypes/tools/codegenerator/codegenerator.py
  comtypes/tools/codegenerator/comments.py
  comtypes/tools/codegenerator/heads.py
  pyproject.toml
Labels: typing, coding style

#745 Reserving blank lines in the generated modules.
  comtypes/tools/codegenerator/codegenerator.py
  comtypes/tools/codegenerator/heads.py
  pyproject.toml
Labels: coding style

#774 Refactor typings and import blocks in `client/__init__.py`, `_post_coinit/misc.py` and `test/test_getactiveobj.py`.
  comtypes/_post_coinit/misc.py
  comtypes/client/__init__.py
  comtypes/test/test_getactiveobj.py
Labels: typing

#776 Add `ActiveObjTest` to `test_comserver`.
  comtypes/test/TestComServer.py
  comtypes/test/test_comserver.py
Labels: tests

#779 [pyproject.toml] Remove unnecessary rules
  pyproject.toml
Labels: coding style
